language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - cd back
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
  - npm run migrate
  - npm run seed:test
  
script:
  - npm test
